const EOFOL_ROOT_ELEMENT_ID = "root"

const EOFOL_ROOT_ELEMENT_ID_PLACEHOLDER = "@root@"

const EOFOL_VIEWS_PLACEHOLDER = "@VIEWS@"

const EOFOL_NAME_PLACEHOLDER = "@EOFOL_NAME@"

const EOFOL_SERVICE_WORKER_FILENAME = "service-worker.js"

const EOFOL_VERBOSITY_LEVEL = 3

const CRYPTO_ID_LENGTH = 17

const EOFOL_NAME = "Eofol5"

module.exports = {
  EOFOL_VERBOSITY_LEVEL,
  EOFOL_ROOT_ELEMENT_ID,
  EOFOL_ROOT_ELEMENT_ID_PLACEHOLDER,
  CRYPTO_ID_LENGTH,
  EOFOL_VIEWS_PLACEHOLDER,
  EOFOL_SERVICE_WORKER_FILENAME,
  EOFOL_NAME,
  EOFOL_NAME_PLACEHOLDER,
}
