 const EOFOL_ROOT_ELEMENT_ID = "root"

 const EOFOL_ROOT_ELEMENT_ID_PLACEHOLDER = "@root@"

 const EOFOL_VERBOSITY_LEVEL = 3

 const CRYPTO_ID_LENGTH = 17

 module.exports = { EOFOL_VERBOSITY_LEVEL,EOFOL_ROOT_ELEMENT_ID,EOFOL_ROOT_ELEMENT_ID_PLACEHOLDER,CRYPTO_ID_LENGTH}
