const { join } = require("../util-compile/fs")

const CWD = process.cwd()

const FILENAME = {
  DIRNAME_PROJECT: "project",
  DIRNAME_SRC: "src",
  DIRNAME_PUBLIC: "public",
  DIRNAME_DIST: "/dist",
  DIRNAME_BUILD: "/build",
  DIRNAME_ASSETS: "assets",
  DIRNAME_JS: "js",
  DIRNAME_CSS: "css",
  DIRNAME_MEDIA: "media",
  DIRNAME_IMAGES: "images",
  DIRNAME_ICONS: "icons",
  DIRNAME_FONTS: "fonts",
}

module.exports = {
  FILENAME,
  PATH: {
    CWD,
    ...FILENAME,
    PATH_DIST: join(CWD, FILENAME.DIRNAME_DIST),
    PATH_BUILD: join(CWD, FILENAME.DIRNAME_BUILD),
    PROJECT: join(CWD, FILENAME.DIRNAME_PROJECT),
    PROJECT_PUBLIC: join(CWD, FILENAME.DIRNAME_PROJECT, FILENAME.DIRNAME_PUBLIC),
    PROJECT_SRC: join(CWD, FILENAME.DIRNAME_PROJECT, FILENAME.DIRNAME_SRC),
    BUILD_ASSETS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS),
    BUILD_ASSETS_JS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_JS),
    BUILD_ASSETS_CSS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_CSS),
    BUILD_ASSETS_MEDIA: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_MEDIA),
    BUILD_ASSETS_MEDIA_IMAGES: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_IMAGES,
    ),
    BUILD_ASSETS_MEDIA_ICONS: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_ICONS,
    ),
    BUILD_ASSETS_MEDIA_FONTS: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_FONTS,
    ),
  },
}
