const { join } = require("../util-compile")

const CWD = process.cwd()

const FILENAME = {
  DIRNAME_PROJECT: "project",
  DIRNAME_SRC: "src",
  DIRNAME_PUBLIC: "public",
  DIRNAME_DIST: "/dist",
  DIRNAME_BUILD: "/build",
  DIRNAME_ASSETS: "assets",
  DIRNAME_JS: "js",
  DIRNAME_CSS: "css",
  DIRNAME_MEDIA: "media",
  DIRNAME_IMAGES: "images",
  DIRNAME_ICONS: "icons",
  DIRNAME_FONTS: "fonts",
  DIRNAME_RESOURCES: "resources",
  DIRNAME_ERROROVERLAY: "error-overlay",
  DIRNAME_SERVICEWORKER: "service-worker",
  DIRNAME_STYLES: "styles",
  DEPENDENCIES: "dependencies",
  EOFOL: "eofol",
  RUNTIME: "runtime",
}

const EXT = {
  JS: ".js",
  CSS: ".css",
  HTML: ".html",
}

module.exports = {
  FILENAME,
  EXT,
  PATH: {
    CWD,
    ...FILENAME,
    PATH_DIST: join(CWD, FILENAME.DIRNAME_DIST),
    PATH_BUILD: join(CWD, FILENAME.DIRNAME_BUILD),
    PROJECT: join(CWD, FILENAME.DIRNAME_PROJECT),
    PROJECT_PUBLIC: join(CWD, FILENAME.DIRNAME_PROJECT, FILENAME.DIRNAME_PUBLIC),
    PROJECT_SRC: join(CWD, FILENAME.DIRNAME_PROJECT, FILENAME.DIRNAME_SRC),
    BUILD_ASSETS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS),
    BUILD_ASSETS_JS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_JS),
    BUILD_ASSETS_CSS: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_CSS),
    BUILD_ASSETS_MEDIA: join(CWD, FILENAME.DIRNAME_BUILD, FILENAME.DIRNAME_ASSETS, FILENAME.DIRNAME_MEDIA),
    BUILD_ASSETS_MEDIA_IMAGES: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_IMAGES,
    ),
    BUILD_ASSETS_MEDIA_ICONS: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_ICONS,
    ),
    BUILD_ASSETS_MEDIA_FONTS: join(
      CWD,
      FILENAME.DIRNAME_BUILD,
      FILENAME.DIRNAME_ASSETS,
      FILENAME.DIRNAME_MEDIA,
      FILENAME.DIRNAME_FONTS,
    ),
    RESOURCES: join(CWD, FILENAME.DIRNAME_RESOURCES),
    RESOURCES_ERROROVERLAY: join(CWD, FILENAME.DIRNAME_RESOURCES, FILENAME.DIRNAME_ERROROVERLAY),
    RESOURCES_SERVICEWORKER: join(CWD, FILENAME.DIRNAME_RESOURCES, FILENAME.DIRNAME_SERVICEWORKER),
    RESOURCES_STYLES: join(CWD, FILENAME.DIRNAME_RESOURCES, FILENAME.DIRNAME_STYLES),
  },
}
